/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class box {
    constructor() {
        this.time = undefined;
        this.oxygen = 0.0;
        this.ph = 7.0;
        this.temperature = 20.0;
        this.salt = 1.0;
        this.nitrite = 1.0;
        this.ammonia = 1.0;
        this.name = "0-0-0";
        this.name_and_time = "0000";
    }

    setTime(time) {
        this.time = time;
    }

    getTime() {
        return this.time;
    }

    setOxygen(oxygen) {
        this.oxygen = oxygen;
    }

    getOxygen() {
        return this.oxygen;
    }

    setPh(ph) {
        this.ph = ph;
    }

    getPh() {
        return this.ph;
    }

    setTemperature(temperature) {
        this.temperature = temperature;
    }

    getTemperature() {
        return this.temperature;
    }

    setSalt(salt) {
        this.salt = salt;
    }

    getSalt() {
        return this.salt;
    }

    setNitrite(nitrite) {
        this.nitrite = nitrite;
    }

    getNitrite() {
        return this.nitrite;
    }

    setAmmonia(ammonia) {
        this.ammonia = ammonia;
    }

    getAmmonia() {
        return this.ammonia;
    }

    setName(name) {
        this.name = name;
    }

    getName() {
        return this.name;
    }

    setName_and_time(name_and_time) {
        this.name_and_time = name_and_time;
    }

    getName_and_time() {
        return this.name_and_time;
    }
}

box.className = 'box';

export {box}